module.exports = {
  up: async (queryInterface) => {
    await queryInterface.bulkInsert('drinks', [
      {
        "idDrink": "15997",
        "strDrink": "GG",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Optional alcohol",
        "strGlass": "Collins Glass",
        "strInstructions": "Pour the Galliano liqueur over ice. Fill the remainder of the glass with ginger ale and thats all there is to it. You now have a your very own GG.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg",
        "strIngredient1": "Galliano",
        "strIngredient2": "Ginger ale",
        "strIngredient3": "Ice",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "2 1/2 shots ",
        "strMeasure2": "",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-07-18 22:06:00"
      },
      {
        "idDrink": "17222",
        "strDrink": "A1",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail Glass",
        "strInstructions": "Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg",
        "strIngredient1": "Gin",
        "strIngredient2": "Grand Marnier",
        "strIngredient3": "Lemon Juice",
        "strIngredient4": "Grenadine",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 3/4 shot ",
        "strMeasure2": "1 Shot ",
        "strMeasure3": "1/4 Shot",
        "strMeasure4": "1/8 Shot",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-07 21:42:09"
      },
      {
        "idDrink": "15288",
        "strDrink": "252",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Add both ingredients to shot glass, shoot, and get drunk quick",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rtpxqw1468877562.jpg",
        "strIngredient1": "151 proof rum",
        "strIngredient2": "Wild Turkey",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/2 shot Bacardi ",
        "strMeasure2": "1/2 shot ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-07-18 22:32:42"
      },
      {
        "idDrink": "14229",
        "strDrink": "747",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "pour kaluha, then Baileys, then Frangelico not chilled and not layered -- SERVE!!!",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xxsxqy1472668106.jpg",
        "strIngredient1": "Kahlua",
        "strIngredient2": "Baileys irish cream",
        "strIngredient3": "Frangelico",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/3 part ",
        "strMeasure2": "1/3 part ",
        "strMeasure3": "1/3 part ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "dateModified": "2016-08-31 19:28:26"
      },
      {
        "idDrink": "17203",
        "strDrink": "Kir",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Wine Glass",
        "strInstructions": "Add the crème de cassis to the bottom of the glass, then top up with wine.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg",
        "strIngredient1": "Creme de Cassis",
        "strIngredient2": "Champagne",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 part ",
        "strMeasure2": "5 parts ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-02 17:38:14"
      },
      {
        "idDrink": "13501",
        "strDrink": "ABC",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Layered in a shot glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg",
        "strIngredient1": "Amaretto",
        "strIngredient2": "Baileys irish cream",
        "strIngredient3": "Cognac",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/3 ",
        "strMeasure2": "1/3 ",
        "strMeasure3": "1/3 ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-08-31 19:32:08"
      },
      {
        "idDrink": "17225",
        "strDrink": "Ace",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Martini Glass",
        "strInstructions": "Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg",
        "strIngredient1": "Gin",
        "strIngredient2": "Grenadine",
        "strIngredient3": "Heavy cream",
        "strIngredient4": "Milk",
        "strIngredient5": "Egg White",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "2 shots ",
        "strMeasure2": "1/2 shot ",
        "strMeasure3": "1/2 shot ",
        "strMeasure4": "1/2 shot ",
        "strMeasure5": "1/2 Fresh",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-07 22:05:06"
      },
      {
        "idDrink": "17141",
        "strDrink": "Smut",
        "strCategory": "Punch / Party Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Beer mug",
        "strInstructions": "Throw it all together and serve real cold.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg",
        "strIngredient1": "Red wine",
        "strIngredient2": "Peach schnapps",
        "strIngredient3": "Pepsi Cola",
        "strIngredient4": "Orange juice",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/3 part ",
        "strMeasure2": "1 shot ",
        "strMeasure3": "1/3 part ",
        "strMeasure4": "1/3 part ",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-02 16:23:32"
      },
      {
        "idDrink": "17208",
        "strDrink": "Rose",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg",
        "strIngredient1": "gin",
        "strIngredient2": "Peach Bitters",
        "strIngredient3": "Mint",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "6 cl",
        "strMeasure2": "2 dashes",
        "strMeasure3": "2 Fresh leaves",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-02 11:45:56"
      },
      {
        "idDrink": "15853",
        "strDrink": "B-52",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Layer ingredients into a shot glass. Serve with a stirrer.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/5a3vg61504372070.jpg",
        "strIngredient1": "Baileys irish cream",
        "strIngredient2": "Grand Marnier",
        "strIngredient3": "Kahlua",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/3 ",
        "strMeasure2": "1/3 ",
        "strMeasure3": "1/4 ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-02 18:07:51"
      },
      {
        "idDrink": "17837",
        "strDrink": "Adam",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg",
        "strIngredient1": "Dark rum",
        "strIngredient2": "Lemon juice",
        "strIngredient3": "Grenadine",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "2 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "1 tsp ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-09-02 11:29:29"
      },
      {
        "idDrink": "14610",
        "strDrink": "ACID",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Shot glass",
        "strInstructions": "Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg",
        "strIngredient1": "151 proof rum",
        "strIngredient2": "Wild Turkey",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 oz Bacardi ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-11-15 11:28:37"
      },
      {
        "idDrink": "13332",
        "strDrink": "B-53",
        "strCategory": "Shot",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Collins Glass",
        "strInstructions": "Layer the Kahlua, Sambucca and Grand Marnier into a shot glas in that order. Better than B-52",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rwqxrv1461866023.jpg",
        "strIngredient1": "Kahlua",
        "strIngredient2": "Sambuca",
        "strIngredient3": "Grand Marnier",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/3 shot ",
        "strMeasure2": "1/3 shot ",
        "strMeasure3": "1/3 shot ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-04-28 18:53:43"
      },
      {
        "idDrink": "13938",
        "strDrink": "AT&T",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball Glass",
        "strInstructions": "Pour Vodka and Gin over ice, add Tonic and Stir",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg",
        "strIngredient1": "Absolut Vodka",
        "strIngredient2": "Gin",
        "strIngredient3": "Tonic water",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "4 oz ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-04-24 22:00:19"
      },
      {
        "idDrink": "16262",
        "strDrink": "H.D.",
        "strCategory": "Coffee / Tea",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Beer mug",
        "strInstructions": "Mix the whisky and Baileys Cream in a beer-glass (at least 50 cl). Fill the rest of the glass with coffee.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/upusyu1472667977.jpg",
        "strIngredient1": "Whisky",
        "strIngredient2": "Baileys irish cream",
        "strIngredient3": "Coffee",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "4 cl ",
        "strMeasure2": "8 cl ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-08-31 19:26:18"
      },
      {
        "idDrink": "17833",
        "strDrink": "A. J.",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake ingredients with ice, strain into a cocktail glass, and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg",
        "strIngredient1": "Applejack",
        "strIngredient2": "Grapefruit juice",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 1/2 oz ",
        "strMeasure2": "1 oz ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-09-02 11:16:58"
      },
      {
        "idDrink": "14598",
        "strDrink": "50/50",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Collins Glass",
        "strInstructions": "fill glass with crushed ice. Add vodka. Add a splash of grand-marnier. Fill with o.j.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/wwpyvr1461919316.jpg",
        "strIngredient1": "Vanilla vodka",
        "strIngredient2": "Grand Marnier",
        "strIngredient3": "Orange juice",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "2 1/2 oz ",
        "strMeasure2": "1 splash ",
        "strMeasure3": "Fill with ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2016-04-29 09:41:56"
      },
      {
        "idDrink": "12776",
        "strDrink": "Melya",
        "strCategory": "Coffee / Tea",
        "strAlcoholic": "Non alcoholic",
        "strGlass": "Coffee mug",
        "strInstructions": "Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg",
        "strIngredient1": "Espresso",
        "strIngredient2": "Honey",
        "strIngredient3": "Cocoa powder",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "",
        "strMeasure2": "Unsweetened ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2015-09-03 03:32:59"
      },
      {
        "idDrink": "12764",
        "strDrink": "Karsk",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg",
        "strIngredient1": "Coffee",
        "strIngredient2": "Grain alcohol",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 part ",
        "strMeasure2": "2 parts ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-02-20 14:54:31"
      },
      {
        "idDrink": "17254",
        "strDrink": "Bijou",
        "strCategory": "Cocktail",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Stir in mixing glass with ice and strain\r\n",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/rysb3r1513706985.jpg",
        "strIngredient1": "Orange Bitters",
        "strIngredient2": "Green Chartreuse",
        "strIngredient3": "Gin",
        "strIngredient4": "Sweet Vermouth",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1 dash",
        "strMeasure2": "1 oz",
        "strMeasure3": "1 oz",
        "strMeasure4": "1 oz",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-12-19 18:09:45"
      },
      {
        "idDrink": "17187",
        "strDrink": "Derby",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Pour all ingredients into a mixing glass with ice. Stir. Strain into a cocktail glass. Garnish with a sprig of fresh mint in the drink.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/52weey1606772672.jpg",
        "strIngredient1": "gin",
        "strIngredient2": "Peach Bitters",
        "strIngredient3": "Mint",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "6 cl",
        "strMeasure2": "2 dashes",
        "strMeasure3": "2 Fresh leaves",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-02 11:45:56"
      },
      {
        "idDrink": "15328",
        "strDrink": "Zorro",
        "strCategory": "Coffee / Tea",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Coffee Mug",
        "strInstructions": "add all and pour black coffee and add whipped cream on top.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg",
        "strIngredient1": "Sambuca",
        "strIngredient2": "Baileys irish cream",
        "strIngredient3": "White Creme de Menthe",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "2 cl ",
        "strMeasure2": "2 cl ",
        "strMeasure3": "2 cl ",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-01-28 16:34:43"
      },
      {
        "idDrink": "16031",
        "strDrink": "Radler",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Highball glass",
        "strInstructions": "Pour beer into large mug, slowly add the 7-up (or Sprite).",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xz8igv1504888995.jpg",
        "strIngredient1": "Beer",
        "strIngredient2": "7-Up",
        "strIngredient3": "",
        "strIngredient4": "",
        "strIngredient5": "",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "12 oz ",
        "strMeasure2": "12 oz ",
        "strMeasure3": "",
        "strMeasure4": "",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-08 17:43:15"
      },
      {
        "idDrink": "11872",
        "strDrink": "Orgasm",
        "strCategory": "Ordinary Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Cocktail glass",
        "strInstructions": "Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg",
        "strIngredient1": "Creme de Cacao",
        "strIngredient2": "Amaretto",
        "strIngredient3": "Triple sec",
        "strIngredient4": "Vodka",
        "strIngredient5": "Light cream",
        "strIngredient6": "",
        "strIngredient7": "",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "1/2 oz white ",
        "strMeasure2": "1/2 oz ",
        "strMeasure3": "1/2 oz ",
        "strMeasure4": "1/2 oz ",
        "strMeasure5": "1 oz ",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-09-08 16:55:14"
      },
      {
        "idDrink": "15691",
        "strDrink": "Zoksel",
        "strCategory": "Soft Drink",
        "strAlcoholic": "Alcoholic",
        "strGlass": "Beer pilsner",
        "strInstructions": "No specific mixinginstructions, just poor every ingredient in one glass. The lemon goes with it.",
        "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ft8ed01485620930.jpg",
        "strIngredient1": "Beer",
        "strIngredient2": "Root beer",
        "strIngredient3": "Lemonade",
        "strIngredient4": "Coca-Cola",
        "strIngredient5": "7-Up",
        "strIngredient6": "Creme de Cassis",
        "strIngredient7": "Lemon",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strMeasure1": "",
        "strMeasure2": "",
        "strMeasure3": "",
        "strMeasure4": "slice\n",
        "strMeasure5": "",
        "strMeasure6": "",
        "strMeasure7": "",
        "strMeasure8": "",
        "strMeasure9": "",
        "strMeasure10": "",
        "strMeasure11": "",
        "strMeasure12": "",
        "strMeasure13": "",
        "strMeasure14": "",
        "strMeasure15": "",
        "dateModified": "2017-01-28 16:28:50"
      }
    ], {});
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('drinks', null, {});
  },
};
